Ext.application({
  extend: "Ext.app.Application",
  name: "TOOLZA",
  requires: ["TOOLZA.view.ux.ActionSheet"],
  stores: [],
  appFolder: "./app",
  launch() {
    var isDarkTheme = chrome.devtools.panels.themeName === "dark";
    var lightVars = {
      "--base-loader-bg-color": "#f6f6f6",
      "--base-loader-color": "#36C",
      "--base-color": "#36c",
      "--base-highlight-color": "#64b5f6",
      "--base-light-color": "#bbdefb",
      "--base-dark-color": "#1976d2",
      "--base-pressed-color": "#7094db",
      "--base-focused-color": "#42a5f5",
      "--base-invisible-color": "rgba(51, 102, 204, 0)",
      "--base-foreground-color": "#fff",
      "--accent-color": "#ff9800",
      "--accent-light-color": "#ffe0b2",
      "--accent-dark-color": "#f57c00",
      "--accent-pressed-color": "#ffb74d",
      "--accent-invisible-color": "rgba(255, 152, 0, 0)",
      "--accent-foreground-color": "#222",
      "--confirm-color": "#7cb342",
      "--confirm-pressed-color": "#a2cc75",
      "--alert-color": "#c62828",
      "--alert-pressed-color": "#de5c5c",
      "--color": "#111",
      "--reverse-color": "#fff",
      "--highlight-color": "rgba(17, 17, 17, 0.54)",
      "--disabled-color": "rgba(17, 17, 17, 0.38)",
      "--reverse-disabled-color": "rgba(255, 255, 255, 0.38)",
      "--divider-color": "#e2e2e2",
      "--selected-background-color": "#e0e0e0",
      "--hovered-background-color": "#eee",
      "--header-background-color": "#f5f5f5",
      "--faded-color": "#e1e1e1",
      "--background-color": "#fafafa",
      "--alt-background-color": "#f5f5f5",
      "--reverse-background-color": "#303030",
      "--reverse-alt-background-color": "#3a3a3a",
      "--overlay-color": "rgba(0, 0, 0, 0.03)",
      "--content-padding": "16px",
      "--listitem-selected-background-color": "#e0e0e0",
      "--base_color_name": '"blue"',
      "--accent_color_name": '"orange"',
      "--dataview_item_selected_background_color": "#e0e0e0",
      "--dataitem_selected_background_color": "#e0e0e0",
      "--dark-mode": "false;",
    };
    var darkVars = {
      "--base-loader-bg-color": "#f6f6f6",
      "--base-loader-color": "#36C",
      "--base-color": "#678",
      "--base-highlight-color": "#64b5f6",
      "--base-light-color": "#bbdefb",
      "--base-dark-color": "#1976d2",
      "--base-pressed-color": "#45515c",
      "--base-focused-color": "#42a5f5",
      "--base-invisible-color": "rgba(102, 119, 136, 0)",
      "--base-foreground-color": "#fff",
      "--accent-color": "#ff9800",
      "--accent-light-color": "#ffe0b2",
      "--accent-dark-color": "#f57c00",
      "--accent-pressed-color": "#b36a00",
      "--accent-invisible-color": "rgba(255, 152, 0, 0)",
      "--accent-foreground-color": "#222",
      "--confirm-color": "#7cb342",
      "--confirm-pressed-color": "#557b2d",
      "--alert-color": "#c62828",
      "--alert-pressed-color": "#861b1b",
      "--color": "#fff",
      "--reverse-color": "#222",
      "--highlight-color": "rgba(255, 255, 255, 0.54)",
      "--disabled-color": "rgba(255, 255, 255, 0.38)",
      "--reverse-disabled-color": "rgba(34, 34, 34, 0.38)",
      "--divider-color": "#3d3d3d",
      "--selected-background-color": "#232425",
      "--hovered-background-color": "#4d4d4d",
      "--header-background-color": "#424242",
      "--faded-color": "#4d4d4d",
      "--background-color": "#303030",
      "--alt-background-color": "#3a3a3a",
      "--reverse-background-color": "#fafafa",
      "--reverse-alt-background-color": "#f5f5f5",
      "--overlay-color": "rgba(255, 255, 255, 0.03)",
      "--content-padding": "16px",
      "--listitem-selected-background-color": "#1976d2",
      "--base_color_name": '"blue"',
      "--accent_color_name": '"orange"',
      "--dataview_item_selected_background_color": "#1976d2",
      "--dataitem_selected_background_color": "#1976d2",
      "--dark-mode": "true;",
    };

    Ext.Object.getKeys(isDarkTheme ? darkVars : lightVars).forEach((k) => {
      document.documentElement.style.setProperty(
        k,
        (isDarkTheme ? darkVars : lightVars)[k]
      );
    });

    Ext.create("TOOLZA.view.Main", {
      fullscreen: true,
    });

    Ext.Viewport.add({
      xtype: "main_actionsheet",
      id: "main_actionsheet",
      modal: false,
      width: "70%",
      minWidth: 120,
      maxWidth: 600,
      side: "right",
      cls: "display-values",
    });
  },
});
